[CmdletBinding()]
param(
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',
    [string]$RepositoryRoot = (Join-Path $PSScriptRoot '..'),
    [string]$BuildProfilePath = (Join-Path $PSScriptRoot '..\config\build-profile.json'),
    [string]$Msys2Root,
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-AbsolutePath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$BasePath
    )

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }

    return [System.IO.Path]::GetFullPath((Join-Path $BasePath $Path))
}

function Convert-ToConanPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    return [System.IO.Path]::GetFullPath($Path).Replace('\', '/')
}

$resolvedRepositoryRoot = Get-AbsolutePath -Path $RepositoryRoot -BasePath (Get-Location).Path
$resolvedBuildProfilePath = Get-AbsolutePath -Path $BuildProfilePath -BasePath $resolvedRepositoryRoot
$resolvedOutputPath = Get-AbsolutePath -Path $OutputPath -BasePath $resolvedRepositoryRoot
$buildProfile = & (Join-Path $PSScriptRoot 'Get-SquidBuildProfile.ps1') -ConfigPath $resolvedBuildProfilePath
$toolchain = & (Join-Path $PSScriptRoot 'Resolve-Msys2Root.ps1') -RepositoryRoot $resolvedRepositoryRoot -BuildProfilePath $resolvedBuildProfilePath -Msys2Root $Msys2Root
$pkgConfigPath = Join-Path $toolchain.MingwBinPath "$([string]$buildProfile.hostTriplet)-pkg-config.exe"
$requiredToolPaths = @(
    $toolchain.BashPath,
    $toolchain.ConanMakePath,
    $toolchain.GccPath,
    $toolchain.GppPath,
    $toolchain.ArPath,
    $toolchain.RanlibPath,
    $toolchain.StripPath,
    $pkgConfigPath
)
$missingToolPaths = $requiredToolPaths | Where-Object { -not (Test-Path -LiteralPath $_) }

if ($missingToolPaths) {
    throw "The MSYS2 toolchain at $($toolchain.Root) is missing required tools: $($missingToolPaths -join ', ')."
}

$compilerVersionText = ((& $toolchain.GccPath -dumpfullversion -dumpversion) 2>&1 | Select-Object -First 1 | Out-String).Trim()
if (-not $compilerVersionText) {
    $compilerVersionText = ((& $toolchain.GccPath --version | Select-Object -First 1) | Out-String).Trim()
}

$compilerVersion = $null
if ($compilerVersionText -match '^(?<version>\d+(?:\.\d+)*)$') {
    $compilerVersion = $Matches.version.Split('.')[0]
} elseif ($compilerVersionText -match '(?<version>\d+(?:\.\d+)*)') {
    $compilerVersion = $Matches.version.Split('.')[0]
}

if (-not $compilerVersion) {
    throw "Unable to determine the GCC version from $($toolchain.GccPath)."
}

$profileLines = @(
    '# Generated by scripts\Write-ConanMsys2Profile.ps1. Do not hand-edit.',
    '[settings]',
    'os=Windows',
    'arch=x86_64',
    'compiler=gcc',
    "compiler.version=$compilerVersion",
    "compiler.cppstd=$([string]$buildProfile.compilerCppStd)",
    "compiler.libcxx=$([string]$buildProfile.compilerLibCxx)",
    "compiler.exception=$([string]$buildProfile.compilerException)",
    "compiler.threads=$([string]$buildProfile.compilerThreads)",
    "build_type=$Configuration",
    '',
    '[conf]',
    "tools.build:compiler_executables={""c"":""$(Convert-ToConanPath -Path $toolchain.GccPath)"",""cpp"":""$(Convert-ToConanPath -Path $toolchain.GppPath)""}",
    "tools.gnu:host_triplet=$([string]$buildProfile.hostTriplet)",
    "tools.gnu:make_program=$(Convert-ToConanPath -Path $toolchain.ConanMakePath)",
    'tools.microsoft.bash:active=True',
    'tools.microsoft.bash:subsystem=msys2',
    "tools.microsoft.bash:path=$(Convert-ToConanPath -Path $toolchain.BashPath)",
    '',
    '[buildenv]',
    "MSYSTEM=$($toolchain.Msys2Env)",
    'CHERE_INVOKING=1',
    "CC=$(Convert-ToConanPath -Path $toolchain.GccPath)",
    "CXX=$(Convert-ToConanPath -Path $toolchain.GppPath)",
    "AR=$(Convert-ToConanPath -Path $toolchain.ArPath)",
    "RANLIB=$(Convert-ToConanPath -Path $toolchain.RanlibPath)",
    "STRIP=$(Convert-ToConanPath -Path $toolchain.StripPath)",
    "PKG_CONFIG=$(Convert-ToConanPath -Path $pkgConfigPath)"
)
$profileContent = ($profileLines -join [Environment]::NewLine) + [Environment]::NewLine
$profileDirectory = Split-Path -Parent $resolvedOutputPath

if ($profileDirectory -and -not (Test-Path -LiteralPath $profileDirectory)) {
    $null = New-Item -ItemType Directory -Path $profileDirectory -Force
}

Set-Content -LiteralPath $resolvedOutputPath -Value $profileContent -Encoding utf8

[PSCustomObject]@{
    OutputPath = $resolvedOutputPath
    CompilerVersion = $compilerVersion
    Msys2Root = $toolchain.Root
    BashPath = $toolchain.BashPath
    GccPath = $toolchain.GccPath
    PkgConfigPath = $pkgConfigPath
    Configuration = $Configuration
}
